jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -106,11 +106,11 @@ pipeline {
             steps {
                 script {
                     def targetEnv = (env.BRANCH_NAME == 'main') ? 'prod' : 'dev'
-                    
+                    def INGRESS_LB_HOST = ""
+                    def NEXUS_IP_VAL = ""
                     echo "=============================================="
                     echo "    DEPLOYING TO ENVIRONMENT: ${targetEnv}    "
                     echo "=============================================="
-
                     withCredentials([
                         [$class: 'AmazonWebServicesCredentialsBinding', 
                             credentialsId: 'aws-cred', 
@@ -121,70 +121,63 @@ pipeline {
                             passwordVariable: 'NEX_PASS'),
                         string(credentialsId: 'db-uri-secret', variable: 'DB_CONN_STRING')
                     ]) {
+                        echo "--- Connecting to Cluster (Authentication) ---"
+                        sh "aws eks update-kubeconfig --name todo-application --region ${env.AWS_REGION}"
+                        
+                        echo "--- Fetching Ingress Controller LoadBalancer ---"
+                        try {
+                            INGRESS_LB_HOST = sh(
+                                script: "kubectl get svc external-ingress-nginx-controller -n ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'",
+                                returnStdout: true
+                            ).trim()
+                        } catch (Exception e) {
+                            echo " Warning: Could not fetch Ingress Host. Ensure Controller is running."
+                        }
+                        
+                        echo "Ingress Controller Host is: ${INGRESS_LB_HOST}"
+                        if (INGRESS_LB_HOST == "") {
+                            error "Error: INGRESS_LB_HOST is empty! Check 'external-ingress-nginx-controller' service in 'ingress' namespace."
+                        }
+
                         echo "--- Fetching Nexus Private IP ---"
-                        def NEXUS_IP_VAL = sh(
+                        NEXUS_IP_VAL = sh(
                             script: "aws ec2 describe-instances --region ${env.AWS_REGION} --filters \"Name=tag:Name,Values=${env.NEXUS_INSTANCE_NAME}\" \"Name=instance-state-name,Values=running\" --query \"Reservations[0].Instances[0].PrivateIpAddress\" --output text",
                             returnStdout: true
                         ).trim()
-                        
                         echo "Nexus Private IP is: ${NEXUS_IP_VAL}"
+                            
                         sh """
                             export AWS_DEFAULT_REGION=${env.AWS_REGION}
-
-                            # Config EKS
-                            echo "--- Connecting to Cluster ---"
-                            aws eks update-kubeconfig --name todo-application --region ${env.AWS_REGION}
 
                             # Create Namespace
                             kubectl create namespace ${targetEnv} || true
 
-                            # Secrets
-                            # A) DB Secret
+                            # Secrets Setup
                             kubectl delete secret db-secret -n ${targetEnv} || true
-                            kubectl create secret generic db-secret \
-                                --from-literal=mongoDbUrl='${DB_CONN_STRING}' \
-                                -n ${targetEnv}
+                            kubectl create secret generic db-secret --from-literal=mongoDbUrl='${DB_CONN_STRING}' -n ${targetEnv}
 
-                            # B) Nexus Secret (Using the Groovy Variable)
                             kubectl delete secret nexus-secret -n ${targetEnv} || true
                             kubectl create secret docker-registry nexus-secret --docker-server="${NEXUS_IP_VAL}:5000" --docker-username="\${NEX_USER}" --docker-password="\${NEX_PASS}" -n ${targetEnv}
                             
                             echo "--- Replacing Placeholders in YAML files ---"
                             sed -i "s|NEXUS_IP_PLACEHOLDER|${NEXUS_IP_VAL}|g" ./k8s/${targetEnv}/3-app-deployment.yaml
                             sed -i "s|DB_URI_PLACEHOLDER|${DB_CONN_STRING}|g" ./k8s/${targetEnv}/3-app-deployment.yaml
+                            sed -i 's|INGRESS_HOST_PLACEHOLDER|${INGRESS_LB_HOST}|g' ./k8s/${targetEnv}/6-ingress.yaml
                             
-                            # Apply Files
+                            # Clean & Apply
                             echo "--- Cleaning up conflicting Secret files ---"
-                            rm -f ./k8s/${targetEnv}/2-nexus-secret.yaml
+                            rm -f ./k8s/${targetEnv}/2-nexus-secret.yaml || true
                             rm -f ./k8s/${targetEnv}/*secret*.yaml || true
                             
                             echo "--- Applying Manifests ---"
                             kubectl apply -f ./k8s/${targetEnv} -n ${targetEnv}
                             
-                            # LoadBalancer Check
-                            echo "--- Waiting for LoadBalancer Hostname (Max 5 mins) ---"
-                            LB_HOST=""
-                            for i in \$(seq 1 30); do
-                                CURRENT_HOST=\$(kubectl get svc external-ingress-nginx-controller -n ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)
-                                if [ -n "\$CURRENT_HOST" ]; then
-                                    LB_HOST=\$CURRENT_HOST
-                                    echo "Found Hostname: \$LB_HOST"
-                                    break
-                                fi
-                                echo "Attempt \$i/30: Waiting 10s for AWS to provision LoadBalancer..."
-                                sleep 10
-                            done
-                            if [ -z "\$LB_HOST" ]; then
-                                echo "ERROR: LoadBalancer Hostname not assigned after 5 minutes."
-                                echo "Check AWS Console -> EC2 -> Load Balancers for issues."
-                                exit 1
-                            else
-                                echo "================================================="
-                                echo " DEPLOYMENT SUCCESSFUL!"
-                                echo " App URL: http://\$LB_HOST"
-                                echo "================================================="
-                                # curl -I --connect-timeout 5 http://\$LB_HOST || true
-                            fi
+                            
+                            
+                            echo "================================================="
+                            echo " DEPLOYMENT SUCCESSFUL!"
+                            echo " App URL: http://${INGRESS_LB_HOST}"
+                            echo "================================================="
                         """
                     }
                 }
